### ISSUE TITLE
Problem running example

### ISSUE THREAD

**Issue by bahmutov** [lumpy-turnips/minty#51]
Hi,
Trying to run simple example, I have created simple `index.js` and `minty.js` with following
```js
// minty.js
const minty = require('minty')
minty.file(require('path').join(__dirname, 'index.js'))
```
I get the jquery error (-1 is correct console log print from index.js)
```sh
$ node minty.js 
-1
Minty has finished analyzing index.js
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/gleb/git/test-minty/node_modules/minty/node_modules/jquery/dist/jquery.min.js'
    at Error (native)
```

**Comment by tzilist** [comment]
Thanks for catching this - this issue has been fixed.

Let me know what else you find!

**Comment by bahmutov** [comment]
ohhh, this is some kind of magic! nice!
Always wanted to get coverage by input data in my functions, not by statement, this is a great idea and implementation. Good job guys

**Comment by tzilist** [comment]
Thanks, we really appreciate that! It's still a bit buggy but hopefully it's helpful to some extent!

**Comment by bahmutov** [comment]
Thanks for fixing this, I made a little repo with example and gif
https://github.com/bahmutov/minty-example

**Comment by angieyeh** [comment]
Hey Gleb, thanks for checking Minty out. I'm glad you like it! If there's
anything you'd like to see from Minty, please let us know. Thank you!


On Thu, Apr 7, 2016 at 2:27 PM, Gleb Bahmutov <notifications@github.com>
wrote:

> Thanks for fixing this, I made a little repo with example and gif
> https://github.com/bahmutov/minty-example
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lumpy-turnips/minty/issues/51#issuecomment-207094536>
>



-- 
Sincerely,
Angie Yeh
University of Southern California | Marshall School of Business
Class of 2014 | Business Administration, B.S.
Cell: (626) 497-1991 | angieyeh24@gmail.com

**Comment by tzilist** [comment]
Hey Gleb, do you mind if we link your example in our readme?

**Comment by bahmutov** [comment]
No problem at all, fell free to grab the link / gif anything ! Thanks for good project, this might just push me to finally do the data coverage project I always wanted for unit tests (unlike statement covers Istanbul)

**Comment by tzilist** [comment]
Hah, you're welcome. I've added your writeup to the read.me and gave you credit :)

Thanks again !
