### ISSUE TITLE
does this even work? :)

### ISSUE THREAD

**Issue by vitaly-t** [lumpy-turnips/minty#65]
When I try using this code:

``` js
minty.file(path.join(__dirname, 'test.js'));
```

in any combination, it never works, always complaining about some path-related issues, like this one:

```
{ [Error: ENOENT: no such file or directory, open 'D:\NodeJS\tests\minty\file\D:\NodeJS\tests\test.js_Sun_Apr_17_2016_13-40-35_GMT+0100_(GMT_Daylight_Time).html']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\NodeJS\\tests\\minty\\file\\D:\\NodeJS\\tests\\test.js_Sun_Apr_17_2016_13-40-35_GMT+0100_(GMT_Daylight_Time).html' }
```

I only can make it work by using this:

``` js
minty.file('test.js');
```

Which then produces:

```
#################################################################################
Minty has found an error! Please check the out put of test.js for more details
#################################################################################

Minty has finished analyzing test.js
```

when I check that file, all I'm seeing is this:

![result](https://cloud.githubusercontent.com/assets/5108906/14587072/740d851e-04a3-11e6-9a8f-f5577ebe31a7.png)

No links, no error reporting,...in fact nothing useful at all. What am I missing?

**UPDATE**

On another-re-read... it says:

> Click forward and back to step through your variables' state as your app executes!

When My app executes, it generates that report, and then it's done. How do I do that parallel running to see the app execute?

**Comment by tzilist** [comment]
Hi Vitaly,

Looks like there is an issue when you call minty.file on the same file you are running. I'll have to take a look into it. As far as the first issue, it looks like the path being called is 

```
D:\\NodeJS\\tests\\minty\\file\\D:\\NodeJS\\tests\\test.js_Sun_Apr_17_2016_13-40-35_GMT+0100_(GMT_Daylight_Time).html
```

I'll have to take a look at that too...not sure why that isn't working. Seems odd as you put the correct as you put the correct input in. I'll have to take a look at that too. Thanks for opening the ticket!

**Comment by tzilist** [comment]
I have looked into this, looks like their is a bug when minty.file is called on the file it's located in. Updating the readme now.
