### ISSUE TITLE
decomment

### ISSUE THREAD

**Issue by vitaly-t** [lumpy-turnips/minty#7]
About this code:
```js
minty.splitFile = function splitFile(results, file, callback) {
  results = decomment(results, {
    space: true
  });
  results = decomment(results);
  results = results.split('\n');
  callback(null, results, file);
};
```
May I ask, what the second call into `decomment` is supposed to accomplish? The first one removes all comments, replacing them with white spaces, as per option `space`. And the second one - it won't do anything, imo (I'm the author of `decomment`).

The other bit is interesting:
```js
  results = results.split('\n');
```
It made me realize that I should have exposed the method to correctly determine the End-of-Line a while back, so I did it in [version 0.8.6](https://github.com/vitaly-t/decomment/releases/tag/v.0.8.6) just now.

If you want to use the correct End-of-Line, update to 0.8.6 and use this:
```js
var EOL = decomment.getEOL(results);
results = results.split(EOL);
```

**Comment by tzilist** [comment]
Hi Vitaly,

Thanks for the catching these few things. Our code is pretty new and, frankly, super messy right now. The second line is an oversight from a merge conflict, thanks for finding that. Secondly, thanks for adding that new method. You are awesome. I will update today and take care of that!
